---
- name: Install snapraid
  ansible.builtin.apt:
    name: snapraid
    state: present
  tags:
    - snapraid
    - apt

- name: Install snapraid configuration
  ansible.builtin.template:
    src: snapraid.conf.j2
    dest: /etc/snapraid.conf
    owner: root
    group: root
    mode: "0644"
  tags:
    - snapraid
    - config

- name: Install snapraid systemd units
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ snapraid_systemd_units }}"
  notify: reload systemd
  tags:
    - snapraid
    - systemd

- name: Flush systemd reload handler
  ansible.builtin.meta: flush_handlers
  tags:
    - snapraid

- name: Enable and start snapraid timers
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ snapraid_timers }}"
  tags:
    - snapraid
    - systemd
