---
- name: Raspberry Pi OS Trixie headless base packages
  hosts: local
  become: true
  gather_facts: true

  roles:
    - role: tailscale
      tags:
        - tailscale
    - role: base_packages
      tags:
        - base_packages
    - role: podman_auto_update
      tags:
        - podman_auto_update
    - role: nas_mount
      tags:
        - nas_mount
    - role: nodejs
      tags:
        - nodejs
    - role: jellyfin
      tags:
        - jellyfin
    - role: freshrss
      tags:
        - freshrss
    - role: caddy
      tags:
        - caddy
