---
- name: Raspberry Pi OS Trixie headless base packages
  hosts: local
  become: true
  gather_facts: true

  roles:
    - tailscale
    - base_packages
    - podman_auto_update
    - nas_mount
    - nodejs
    - jellyfin
