---
- name: Raspberry Pi OS Trixie headless base packages
  hosts: local
  become: true
  gather_facts: true

  roles:
    - role: tailscale
      tags:
        - tailscale
    - role: base_packages
      tags:
        - base_packages
    - role: nodejs
      tags:
        - nodejs
    - role: storage
      tags:
        - storage
    - role: snapraid
      tags:
        - snapraid
    - role: nfs
      tags:
        - nfs
    - role: samba
      tags:
        - samba
