---
# Snapraid parity location
snapraid_parity_path: /mnt/parity1/snapraid.parity

# Snapraid content file locations
snapraid_content_paths:
  - /mnt/das1/snapraid.content
  - /mnt/das2/snapraid.content
  - /mnt/das3/snapraid.content
  - /mnt/parity1/snapraid.content

# Snapraid data disks
snapraid_data_disks:
  - { name: d1, path: /mnt/das1 }
  - { name: d2, path: /mnt/das2 }
  - { name: d3, path: /mnt/das3 }

# Snapraid exclude patterns
snapraid_excludes:
  - /lost+found/

# Snapraid systemd unit files
snapraid_systemd_units:
  - snapraid-sync.service
  - snapraid-sync.timer
  - snapraid-scrub.service
  - snapraid-scrub.timer

# Snapraid timers to enable
snapraid_timers:
  - snapraid-sync.timer
  - snapraid-scrub.timer
