---
# Jellyfin container image
jellyfin_image: docker.io/jellyfin/jellyfin:latest

# Network ports
jellyfin_http_port: 8096
jellyfin_autodiscovery_port: 7359
jellyfin_dlna_port: 1900

# Hardware acceleration devices (leave empty to disable)
jellyfin_devices:
  - /dev/video19
  - /dev/dri/renderD128

# Media path on host
jellyfin_media_path: /media/daspool/media
